## 데이터 탐색 및 집계 연산
### 1. 기본 데이터 탐색 함수

In [2]:
import pandas as pd
import numpy as np

In [3]:

# 예시 데이터 생성 (전자상거래 주문 데이터)
order_data = pd.DataFrame({
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005', 'ORD006', 'ORD007', 'ORD008'],
    'customer_id': ['C001', 'C002', 'C001', 'C003', 'C002', 'C004', 'C001', 'C003'],
    'product_category': ['전자제품', '의류', '전자제품', '도서', '의류', '전자제품', '도서', '의류'],
    'order_amount': [150000, 45000, 320000, 25000, 67000, 89000, 35000, 52000],
    'customer_age': [28, 35, 28, 42, 35, 31, 28, 42],
    'region': ['서울', '부산', '서울', '대구', '부산', '서울', '서울', '대구'],
    'order_date': pd.to_datetime(['2024-01-15', '2024-01-16', '2024-01-18', '2024-01-20',
                                  '2024-01-22', '2024-01-25', '2024-01-28', '2024-01-30'])
})

display(order_data)

,order_id,customer_id,product_category,order_amount,customer_age,region,order_date
0,ORD001,C001,전자제품,150000,28,서울,2024-01-15
1,ORD002,C002,의류,45000,35,부산,2024-01-16
2,ORD003,C001,전자제품,320000,28,서울,2024-01-18
3,ORD004,C003,도서,25000,42,대구,2024-01-20
4,ORD005,C002,의류,67000,35,부산,2024-01-22
5,ORD006,C004,전자제품,89000,31,서울,2024-01-25
6,ORD007,C001,도서,35000,28,서울,2024-01-28
7,ORD008,C003,의류,52000,42,대구,2024-01-30

In [4]:
# 기본 데이터 정보 검색
print("=== 데이터프레임 기본 정보 ===")
print(f"데이터 크기: {order_data.shape}")
print(f"컬럼명: {list(order_data.columns)}")

print("\n=== 데이터 타입 정보 ===")
print(order_data.dtypes)

print("\n=== 기술통계량 ===")
print(order_data.describe())

print("\n=== 카테고리별 주문 빈도 ===")
print(order_data['product_category'].value_counts())

print("\n=== 지역별 분포 ===")
print(order_data['region'].value_counts())

print("\n=== 결측치 확인 ===")
print(order_data.isnull().sum())

=== 데이터프레임 기본 정보 ===
데이터 크기: (8, 7)
컬럼명: ['order_id', 'customer_id', 'product_category', 'order_amount', 'customer_age', 'region', 'order_date']

=== 데이터 타입 정보 ===
order_id                       str
customer_id                    str
product_category               str
order_amount                 int64
customer_age                 int64
region                         str
order_date          datetime64[us]
dtype: object

=== 기술통계량 ===
       order_amount  customer_age           order_date
count       8.00000      8.000000                    8
mean    97875.00000     33.625000  2024-01-21 18:00:00
min     25000.00000     28.000000  2024-01-15 00:00:00
25%     42500.00000     28.000000  2024-01-17 12:00:00
50%     59500.00000     33.000000  2024-01-21 00:00:00
75%    104250.00000     36.750000  2024-01-25 18:00:00
max    320000.00000     42.000000  2024-01-30 00:00:00
std     98018.12879      5.926635                  NaN

=== 카테고리별 주문 빈도 ===
product_category
전자제품    3
의류      3
도서      2
Name: count, dtype: int64

=== 지역별 분포 ===
region
서울    4
부산    2
대구    2
Name: count, dtype: int64

=== 결측치 확인 ===
order_id            0
customer_id         0
product_category    0
order_amount        0
customer_age        0
region              0
order_date          0
dtype: int64

### 2. 기술통계량 및 데이터 요약

In [5]:
# 주문금액에 대한 다양한 통계량 계산
amount_stats = order_data['order_amount'].agg(['mean', 'median', 'std', 'min', 'max', 'count'])
print("=== 주문금액 통계량 ===")
print(amount_stats)

# 분위수 계산
print("\n=== 주문금액 분위수 ===")
quantiles = order_data['order_amount'].quantile([0.25, 0.5, 0.75, 0.9])
print(quantiles)

# 고객 연령과 주문금액 간 상관관계
print("\n=== 수치형 변수 간 상관관계 ===")
numeric_corr = order_data[['customer_age', 'order_amount']].corr()
print(numeric_corr)

# 카테고리별 고유값 개수
print("\n=== 각 컬럼별 고유값 개수 ===")
print(order_data.nunique())

=== 주문금액 통계량 ===
mean       97875.00000
median     59500.00000
std        98018.12879
min        25000.00000
max       320000.00000
count          8.00000
Name: order_amount, dtype: float64

=== 주문금액 분위수 ===
0.25     42500.0
0.50     59500.0
0.75    104250.0
0.90    201000.0
Name: order_amount, dtype: float64

=== 수치형 변수 간 상관관계 ===
              customer_age  order_amount
customer_age      1.000000     -0.559552
order_amount     -0.559552      1.000000

=== 각 컬럼별 고유값 개수 ===
order_id            8
customer_id         4
product_category    3
order_amount        8
customer_age        4
region              3
order_date          8
dtype: int64

### 3. 피봇 테이블

In [7]:
# 지역별, 카테고리별 평균 주문금액 피봇테이블
region_category_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc='mean',
    fill_value=0
)
print("=== 지역별 카테고리별 평균 주문금액 ===")
print(region_category_pivot)

=== 지역별 카테고리별 평균 주문금액 ===
product_category       도서       의류           전자제품
region
대구                25000.0  52000.0       0.000000
부산                    0.0  56000.0       0.000000
서울                35000.0      0.0  186333.333333

In [ ]:
# 다중 집계 함수 적용
# 지역별 상품 카테고리별 주문금액 평균, 개수, 합계
multi_agg_pivot = pd.pivot_table(
    order_data,
    values='order_amount',
    index='region',
    columns='product_category',
    aggfunc=['mean', 'count', 'sum'],
    fill_value=0,
    margins=True  # 총합 행/열 추가
)

print("=== 다중 집계 함수 피봇테이블 (일부) ===")
print(multi_agg_pivot['mean'])  # 평균값만 출력

=== 다중 집계 함수 피봇테이블 (일부) ===
product_category       도서            의류           전자제품       All
region
대구                25000.0  52000.000000       0.000000   38500.0
부산                    0.0  56000.000000       0.000000   56000.0
서울                35000.0      0.000000  186333.333333  148500.0
All               30000.0  54666.666667  186333.333333   97875.0

In [9]:
# 고객 연령대별, 지역별 주문 건수
order_data['age_group'] = pd.cut(order_data['customer_age'],
                                bins=[0, 30, 40, 50],
                                labels=['20대', '30대', '40대'])

age_region_pivot = pd.pivot_table(
    order_data,
    values='order_id',
    index='age_group',
    columns='region',
    aggfunc='count',
    fill_value=0
)

print("=== 연령대별 지역별 주문 건수 ===")
print(age_region_pivot)

=== 연령대별 지역별 주문 건수 ===
region     대구  부산  서울
age_group
20대         0   0   3
30대         0   2   1
40대         2   0   0

## 4. 그룹별 집계 연산

In [11]:
# 고객별 주문 통계
customer_stats = order_data.groupby('customer_id').agg({
    'order_amount': ['count', 'sum', 'mean', 'max'],
    'order_id': 'count'
}).round(2)

display(customer_stats)

            order_amount                            order_id
                   count     sum       mean     max    count
customer_id
C001                   3  505000  168333.33  320000        3
C002                   2  112000   56000.00   67000        2
C003                   2   77000   38500.00   52000        2
C004                   1   89000   89000.00   89000        1

In [12]:
# 지역별 상세 분석
region_analysis = order_data.groupby('region').agg({
    'order_amount': ['count', 'sum', 'mean', 'std'],
    'customer_age': 'mean',
    'customer_id': 'nunique'  # 고유 고객 수
}).round(2)

display(region_analysis)

       order_amount                              customer_age customer_id
              count     sum      mean        std         mean     nunique
region
대구                2   77000   38500.0   19091.88        42.00           1
부산                2  112000   56000.0   15556.35        35.00           1
서울                4  594000  148500.0  123608.25        28.75           2

In [13]:
# 상품 카테고리별 월별 주문 트렌드
order_data['order_month'] = order_data['order_date'].dt.month
monthly_category = order_data.groupby(['order_month', 'product_category']).agg({
    'order_amount': ['count', 'sum'],
    'customer_id': 'nunique'
})

print("=== 월별 카테고리별 주문 현황 ===")
print(monthly_category)

# 그룹별 크기와 기술통계
print("=== 지역별 그룹 크기 ===")
print(order_data.groupby('region').size())

=== 월별 카테고리별 주문 현황 ===
                             order_amount         customer_id
                                    count     sum     nunique
order_month product_category
1           도서                          2   60000           2
            의류                          3  164000           2
            전자제품                        3  559000           2
=== 지역별 그룹 크기 ===
region
대구    2
부산    2
서울    4
dtype: int64

In [14]:
print("=== 카테고리별 주문금액 기술통계 ===")
category_describe = order_data.groupby('product_category')['order_amount'].describe()
print(category_describe.round(2))

=== 카테고리별 주문금액 기술통계 ===
                  count       mean        std      min       25%       50%  \
product_category
도서                  2.0   30000.00    7071.07  25000.0   27500.0   30000.0
의류                  3.0   54666.67   11239.81  45000.0   48500.0   52000.0
전자제품                3.0  186333.33  119709.37  89000.0  119500.0  150000.0

                       75%       max
product_category
도서                 32500.0   35000.0
의류                 59500.0   67000.0
전자제품              235000.0  320000.0

## 5. 멀티레벨 인덱스와 고급 집계

In [15]:
# 지역별, 카테고리별, 연령대별 다차원 분석
multi_group_analysis = order_data.groupby(['region', 'product_category', 'age_group']).agg({
    'order_amount': ['count', 'sum', 'mean'],
    'customer_id': 'nunique'
}).round(2)

print("=== 다차원 그룹별 분석 ===")
print(multi_group_analysis.head(10))

=== 다차원 그룹별 분석 ===
                                  order_amount                   customer_id
                                         count     sum      mean     nunique
region product_category age_group
대구     도서               40대                  1   25000   25000.0           1
       의류               40대                  1   52000   52000.0           1
부산     의류               30대                  2  112000   56000.0           1
서울     도서               20대                  1   35000   35000.0           1
       전자제품             20대                  2  470000  235000.0           1
                        30대                  1   89000   89000.0           1

In [16]:
# 멀티인덱스를 컬럼으로 변환
unstacked_data = order_data.groupby(['region', 'product_category'])['order_amount'].sum().unstack(fill_value=0)
print("\n=== 지역-카테고리 행렬 (unstack) ===")
print(unstacked_data)

=== 지역-카테고리 행렬 (unstack) ===
product_category     도서      의류    전자제품
region
대구                25000   52000       0
부산                    0  112000       0
서울                35000       0  559000

In [17]:
# 고급 집계: 사용자 정의 함수
def coefficient_of_variation(x):
    """변동계수 계산 (표준편차/평균)"""
    return x.std() / x.mean() if x.mean() != 0 else 0

advanced_stats = order_data.groupby('region')['order_amount'].agg([
    'mean',
    'std',
    coefficient_of_variation,
    lambda x: x.quantile(0.75) - x.quantile(0.25)  # IQR
]).round(3)

advanced_stats.columns = ['평균', '표준편차', '변동계수', 'IQR']
print("\n=== 지역별 고급 통계량 ===")
print(advanced_stats)

=== 지역별 고급 통계량 ===
              평균        표준편차   변동계수       IQR
region
대구       38500.0   19091.883  0.496   13500.0
부산       56000.0   15556.349  0.278   11000.0
서울      148500.0  123608.252  0.832  117000.0

In [18]:
# 조건부 집계
def conditional_mean(group):
    """고액 주문(10만원 이상)의 평균"""
    high_value = group[group['order_amount'] >= 100000]
    return high_value['order_amount'].mean() if len(high_value) > 0 else 0

conditional_stats = order_data.groupby('region').apply(conditional_mean)
print("\n=== 지역별 고액주문 평균금액 ===")
print(conditional_stats.fillna(0).astype(int))

=== 지역별 고액주문 평균금액 ===
region
대구         0
부산         0
서울    235000
dtype: int64

In [19]:
# 집계 결과의 순위 계산
region_total = order_data.groupby('region')['order_amount'].sum().sort_values(ascending=False)
region_rank = region_total.rank(ascending=False, method='dense')

print("\n=== 지역별 총 주문금액 순위 ===")
result_df = pd.DataFrame({
    '총주문금액': region_total,
    '순위': region_rank.astype(int)
})
print(result_df)

=== 지역별 총 주문금액 순위 ===
         총주문금액  순위
region
서울      594000   1
부산      112000   2
대구       77000   3